"""Textura - Text transformation utilities."""

from .transform import (
    upper,
    lower,
    title,
    sentence,
    alternating,
    sort_lines,
    reverse_lines,
    random_lines,
    sort_by_length,
    dedup_lines,
    dedup_words,
    grep_lines,
    grep_v_lines,
    wrap_text,
    unwrap_text,
    extract_column,
    join_lines,
    split_lines,
)

__all__ = [
    "upper",
    "lower",
    "title",
    "sentence",
    "alternating",
    "sort_lines",
    "reverse_lines",
    "random_lines",
    "sort_by_length",
    "dedup_lines",
    "dedup_words",
    "grep_lines",
    "grep_v_lines",
    "wrap_text",
    "unwrap_text",
    "extract_column",
    "join_lines",
    "split_lines",
]